[build]
  # Run from root, explicitly enter frontend
  base = "/" 
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
